### ISSUE TITLE
docker-entrypoint.sh: permission denied

### ISSUE THREAD

**Issue by bsergik** [WatchDG/docker-wireguard#1]
Hello!

Executing the command
`docker run -d --rm --volume=/etc/wireguard:/etc/wireguard --expose=51820/udp -p=51820:51820/udp --cap-add NET_ADMIN watchdg/wireguard up wg0`
I get the following error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown.

**Comment by WatchDG** [comment]
Thank you for your comment. The fix is ready and applied.
